# Global configuration shared by all profiles
quarkus:
  http:
    port: 8080
  application:
    name: amazoff-users

  hibernate-orm:
    log:
      sql: false
    database:
      generation: update
    
# Development profile configuration
"%dev":
  quarkus:
    datasource:
      db-kind: postgresql
      username: amazoff_user
      password: amazoff_password
      reactive:
        url: vertx-reactive:postgresql://localhost:5432/amazoff_users
    hibernate-orm:
      log:
        sql: true
      sql-load-script: import.sql
      reactive:
        database:
          generation: drop-and-create
    log:
      console:
        level: DEBUG

# Test profile configuration
"%test":
  quarkus:
    datasource:
      db-kind: h2
      jdbc:
        url: jdbc:h2:mem:amazoff_users_test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        driver: org.h2.Driver
      username: sa
      password: ""
    hibernate-orm:
      sql-load-script: import.sql
      reactive:
        database:
          generation: drop-and-create
    log:
      console:
        level: DEBUG

# Production profile configuration
"%prod":
  quarkus:
    datasource:
      db-kind: postgresql
      username: ${DB_USERNAME:postgres}
      password: ${DB_PASSWORD:postgres}
      reactive:
        url: vertx-reactive:postgresql://${DB_HOST:users-db}:${DB_PORT:5432}/${DB_NAME:amazoff}
    hibernate-orm:
      database:
        generation: update
    log:
      console:
        level: DEBUG

    swagger-ui:
      always-include: true
      path: /q/swagger-ui
    smallrye-openapi:
      path: /q/openapi        