name: Deploy Docker Image

on:
  workflow_run:
    workflows: ["SonarQube Scan", "Snyk Vulnerability Scan"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Grant execute permissions to mvnw
      run: chmod +x ./mvnw
        
    - name: Build Quarkus application
      run: ./mvnw package

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set repository name lowercase
      id: repo_name
      run: echo "REPO_LC=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

    - name: Build and push Docker image
      run: |
        docker build -f src/main/docker/Dockerfile.jvm -t ghcr.io/$REPO_LC:latest .
        docker push ghcr.io/$REPO_LC:latest